### ISSUE TITLE
Reading DESCRIPTION fails when empty lines present

### ISSUE THREAD

**Issue by malcolmbarrett** [r-lib/desc#106]
(Discovered investigating https://github.com/r-lib/usethis/issues/1436)

When a `DESCRIPTION` file has an extra space it in, desc trips up and doesn't provide a helpful error message

``` r
desc <- 'Package: desc.empty.line
Title: What the Package Does (One Line, Title Case)
Version: 0.0.0.9000
Authors@R: 
    person(given = "First",
           family = "Last",
           role = c("aut", "cre"),
           email = "first.last@example.com",
           comment = c(ORCID = "YOUR-ORCID-ID"))
Description: What the package does (one paragraph).

License: `use_mit_license()`, `use_gpl3_license()` or friends to pick a
    license
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.1
'

desc::desc(text = desc)
#> Error in if (any(mismatch <- res != res2)) {: missing value where TRUE/FALSE needed
```

<sup>Created on 2021-04-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

The problem seems to be here: https://github.com/r-lib/desc/blob/1a9af2d57b92de577e4cd67f126a4f1461554db6/R/read.R#L18-L29

Essentially, when `read.dcf()` encounters a new line, it treats it as a whole new record and adds a row to the output with whatever is left in the DCF file. 

It seems reasonable for `DESCRIPTION` files to check this in `read_desc()`, e.g.

```r
if (nrow(res)) > 1) {
  stop("Empty lines found in DESCRIPTION file", call. = FALSE)
}
```

Happy to submit a PR if you think that will do the trick, as well as to add a test

**Comment by gaborcsardi** [comment]
> Happy to submit a PR if you think that will do the trick, as well as to add a test

Yes, please!
