### ISSUE TITLE
Helper for licenses?

### ISSUE THREAD

**Issue by hadley** [r-lib/desc#28]
Not entirely sure if this would be useful. But I need to parse for pkgdown so I can automatically add links to licenses.   If it looks like what I implement will be general, I can move the code here.  (But currently I'm guessing it'll be some hacky search & replace of license names with links)

**Comment by gaborcsardi** [comment]
I think it would be useful. I looked at licenses and their validation before, and validation is very difficult, there is also a lot of code for it in R, in `tools`, AFAIR. They also have a lot of code to convert license strings to a canonical form, which we could use, probably.

Anyway, I'll take a look at this, soonish.

**Comment by gaborcsardi** [comment]
Here is the official code: https://github.com/wch/r-source/blob/bdba8962fa1790a3f5df7b8ce429277ed4499de3/src/library/tools/R/license.R

All internal, of course. I don't feel like replicating it. 

I wonder if the standardized license name can be extracted somehow from some check result.....

**Comment by gaborcsardi** [comment]
Aha. You put the license in a dummy package, run `R CMD check` on it, and it spits out the standardized license: 
```
* checking package directory ... OK
* checking DESCRIPTION meta-information ... NOTE
Non-standard license specification:
  GPL 2.0 or newer
Standardizable: TRUE
Standardized license specification:
  GPL (>= 2)
* checking top-level files ... OK
```

I am not sure if this is better than calling the internal method:
```r
❯ tools:::analyze_license("GPL 2.0 or newer")
$is_empty
[1] FALSE

$is_canonical
[1] FALSE

$bad_components
[1] "GPL 2.0 or newer"

$is_standardizable
[1] TRUE

$is_verified
[1] TRUE

$standardization
[1] "GPL (>= 2)"

$components
[1] "GPL (>= 2)"

$expansions
$expansions[[1]]
[1] "GPL-2" "GPL-3"


$extensions
NULL

$pointers
NULL

$is_FOSS
[1] TRUE

$restricts_use
[1] FALSE
```

**Comment by gaborcsardi** [comment]
I think I'll create a separate packages for licenses, with the base R code.

**Comment by gaborcsardi** [comment]
Btw. there is also this: https://github.com/Ironholds/osi/

**Comment by gaborcsardi** [comment]
This will probably not happen in this package, it is too bug, and  I am not even sure what's the right way  to include it. Just copying over all  the code from base R does not feel like the right solution.
