### ISSUE TITLE
Need to translate DESCRIPTION if the specified `Encoding` is not the same as the system encoding.

### ISSUE THREAD

**Issue by jimhester** [r-lib/desc#52]
For instance trying to read the [DESCRIPTION](https://github.com/r-lib/desc/files/1337632/DESCRIPTION.txt) file from the RArcInfo package, which has a declared encoding of latin1 while the session encoding is UTF-8.

```r
desc::desc("RArcInfo/DESCRIPTION.txt")
Warning in grepl(re_maint, x$value) :
  input string 1 is invalid in this locale
Error in gsub(st$close, st$open, text, fixed = TRUE) :
  input string 1 is invalid in this locale
```

Relevant lines from `packageDescription` would seem to address this issue.

https://github.com/wch/r-source/blob/93b33adbcecd4a2577e1d5b873bef9a52fd734b8/src/library/utils/R/indices.R#L76-L106

**Comment by gaborcsardi** [comment]
Just fixed this in eeffa6ee19938c3f374beab1328e5bab19503736.

**Comment by WastlM** [comment]
This should trigger a NEWS item.

**Comment by gaborcsardi** [comment]
@WastlM agreed.
