### ISSUE TITLE
Expose version incrementing logic

### ISSUE THREAD

**Issue by jennybc** [r-lib/desc#61]
Would you be receptive to a  PR that moves version incrementation into an exported helper?

It would be nice to use in, e.g., usethis. Basically present and preview the versions that would result from incrementing major, minor, patch and dev.

Right now desc's logic is locked into the method that actually *does* the incrementing.

https://github.com/r-lib/desc/blob/156519043262b9c1e1b239f983c47b95e34b3bd8/R/version.R#L13-L50

**Comment by gaborcsardi** [comment]
I suppose we could export it, but it is actually not *that* bad to use it via the `description` class:
```r
desc::desc(text = "Version: 1.4.5")$bump_version("minor")$get("Version")[[1]]
```

**Comment by jennybc** [comment]
Aha! This did not occur to me. We'll do this then. Thanks.
