### ISSUE TITLE
get_field()

### ISSUE THREAD

**Issue by hadley** [r-lib/desc#62]
I realise now the semantics I actually wanted with `get_or_fail()` and a better name.

```R
desc$get_field("invalid")
#> Error: Field 'invalid' not found

desc$get_field("invalid", default = NULL)
#> NULL
```

**Comment by hadley** [comment]
We've implemented similar semantics in `rlang::env_get()`

**Comment by gaborcsardi** [comment]
OK, I'll add this, and soft-deprecate `get_or_fail()`.

**Comment by gaborcsardi** [comment]
Although `rlang::env_get()` uses `missing()`, so it is somewhat painful to program it....

**Comment by gaborcsardi** [comment]
Although you can also write it without `missing()`, seemingly:
```r
❯ f <- function(key, default = stop("Field '", key, "' not found")) { if (key == "good") "OK" else default }
❯ f("bad")
Error in f("bad") : Field 'bad' not found
❯ f("good")
[1] "OK"
```
