### ISSUE TITLE
desc::desc() output inconsistent with read.dcf()

### ISSUE THREAD

**Issue by sz-cgt** [r-lib/desc#68]
While somewhat related to #14, this issue is actually about leading white space, not trailing space.

Given this DESCRIPTION
```
Package: test
Title: What the Package Does (one line, title case)
Version: 0.0.0.9000
Authors@R: person("First", "Last", email = "first.last@example.com", role = c("aut", "cre"))
Description: What the package does (one paragraph).
Depends: R (>= 3.5.1)
License: What license is it under?
Encoding: UTF-8
LazyData: true
RoxygenNote: 6.1.0.9000
Collate:
    'b-function.R'
    'a-function.R'
Imports: magrittr,
    readr
```
With `read.dcf()`, you get the following
```
> dcf <- read.dcf("DESCRIPTION")
> dcf[,which(colnames(dcf) == "Collate")]
                         Collate 
"'b-function.R'\n'a-function.R'" 
> dcf[,which(colnames(dcf) == "Imports")]
           Imports 
"magrittr,\nreadr" 
```

However, with `desc::desc()` you get
```
> dcf <- desc::desc("DESCRIPTION")
> dcf$get_field("Collate")
[1] "'b-function.R'\n    'a-function.R'"
> dcf$get_field("Imports")
[1] "magrittr,\n    readr"
```

The additional white space between values causes `roxygen2::parse_package()` to fail when processing a package that uses collation as it results in a list with blank entries that get translated to directory names instead of file names.

While you can make the case that `roxygen2` should be more rigorous in it's checking (klutometis/roxygen#766), you should at least document that the pattern above is not a drop-in replacement for `base::read.dcf()`

**Comment by gaborcsardi** [comment]
desc tries hard to keep the whitespace as is, to minimize reformatting of the file when updating fields. If you want more structured data, instead of the raw text, you can have that as well:
```r
❯ dcf$get_deps()
     type  package  version
1 Depends        R >= 3.5.1
2 Imports magrittr        *
3 Imports    readr        *

❯ dcf$get_collate()
[1] "b-function.R" "a-function.R"
```
