### ISSUE TITLE
Question: should desc_set/set check the things set?

### ISSUE THREAD

**Issue by maelle** [r-lib/desc#74]
I've just made a typo in a function I was writing and set "description" instead of "Description". I'm now wondering whether it'd make sense for `desc` to have a list of possible fields and to error (or a list of most classifical fields, including regexp such as starting with "X-schema.org-").

So this below would either get an error or warning or message:
``` r
descr <- desc::desc("!new")
descr$set(notafield = "blabla")
descr
#> Package: {{ Package }}
#> Title: {{ Title }}
#> Version: 1.0.0
#> Authors@R (parsed):
#>     * Jo Doe <jodoe@dom.ain> [aut, cre]
#> Maintainer: {{ Maintainer }}
#> Description: {{ Description }}
#> License: {{ License }}
#> URL: {{ URL }}
#> BugReports: {{ BugReports }}
#> Encoding: UTF-8
#> LazyData: true
#> notafield: blabla
```

<sup>Created on 2018-10-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Or maybe it doesn't make sense because one _can_ set any field in a DESCRIPTION. 🤔

**Comment by gaborcsardi** [comment]
Yeah, I would not do that. There are other tools to check the  DESCRIPTION. E.g. `R  CMD check` will warn  you.

**Comment by maelle** [comment]
Thanks. Would there be any use for a separate `is_valid()` function that one could run outside of `R CMD check` at the end of a pipeline modifying DESCRIPTION files?

**Comment by gaborcsardi** [comment]
There is a stub for `$validate` but  I am  not entirely  sure  what  it  should do.
