### ISSUE TITLE
Ideas for validate?

### ISSUE THREAD

**Issue by maelle** [r-lib/desc#75]
Messy list of ideas 😸 I'm not sure what's validate vs what's "best-practice"cf https://github.com/r-lib/desc/issues/74#issuecomment-426989817

* valid URLs (`crul::ok()` or `httr` equivalent) anywhere where there's an URL - including checking whether there's a redirect, i.e. when a repo was transferred to a new owner on GitHub, the URL should be changed although the old one is still valid because redirected.
* has the URLs (BugReports, Repository)
* only roles that exist
* no duplicate authors (tricky one when not for exact match)
* the description check that's already done somewhere else (stating it shouldn't start by "This package")
* no duplicate dependency, e.g. the same package twice once under Depends once under Suggests
* no missing necessary field
* no non-accepted field
* ORCIDs (_that_ would be "best-practice" and quite opiniated so probably not in scope)
* Anything that's in `R CMD Check` reg DESCRIPTION except with regard to the rest of the package.

**Comment by gaborcsardi** [comment]
I am not sure if desc should do these, probably not. 

For one, desc is quite low level, and checking all these would  bring in a lot of dependencies. Also, desc aims to be un-opinionated, and as you say, some of these are opinionated. Even omitting `BugReports` and `URL` is  not wrong, just good practice.

I think these would be better implemented in a package like goodpractice, and then you can easily run them by selecting  only this check or  these checks.

**Comment by maelle** [comment]
This makes sense!

**Comment by maelle** [comment]
For reference https://github.com/MangoTheCat/goodpractice/issues/122
