### ISSUE TITLE
Feature request: make it possible to add an author with several roles

### ISSUE THREAD

**Issue by maelle** [r-lib/desc#77]
I.e. change `check_author_args()` and the same thing in `add_me()` to use a function called `is_character_or_null()` instead of `is_string_or_null()`.

E.g. to be able to `add_me(role = c("ctb", "rev"))` or so.

**Comment by gaborcsardi** [comment]
Isn't this fixed by #89?

**Comment by avalcarcel9** [comment]
@gaborcsardi looks like someone got to coding it before me! Glad this feature was incorporated. My issue/feature request can no be closed.

**Comment by maelle** [comment]
> Isn't this fixed by #89?

Not entirely, cf #102
