### ISSUE TITLE
Change formatting of Authors@R under normalization

### ISSUE THREAD

**Issue by jennybc** [r-lib/desc#78]
I've been able to remove lots of code from usethis by delegating various DESCRIPTION operations to desc, which is great.

However one consequence is that we're getting some undesirable re-styling of the Authors@R field (via, e.g. `usethis::use_tidy_description()`.

GOOD, YES:

```
Authors@R: c(
    person("Hadley", "Wickham", , "hadley@rstudio.com", role = c("aut", "cre"), 
      comment = c(ORCID = "0000-0003-4757-117X")
    ),
    person("Jennifer", "Bryan", , "jenny@rstudio.com", role = "aut",
      comment = c(ORCID = "0000-0002-6983-2759")
    ),
    person("RStudio", role = c("cph", "fnd"))
  )
```

BAD, NO:

```
Authors@R: 
    c(person(given = "Hadley",
             family = "Wickham",
             role = c("aut", "cre"),
             email = "hadley@rstudio.com"),
      person(given = "Robby",
             family = "Shaver",
             role = "aut"),
      person(given = "RStudio",
             role = "cph"))
```

If it's OK, it's much nicer to implement this behaviour here and inherit it in usethis. Sound OK?

`usethis::use_tidy_description()` calls `desc$normalize()`, so the thing to change is somewhere inside there.

https://github.com/r-lib/usethis/issues/460

**Comment by gaborcsardi** [comment]
Sure, thanks!
