### ISSUE TITLE
Expose functions for parsing remotes

### ISSUE THREAD

**Issue by nuest** [r-lib/desc#82]
I am using functions from this package to parse the `Remotes` field of a `DESCRIPTION` file, namely

- `remotes:::parse_one_remote`
- `remotes:::split_remotes`

I understand these are not complex methods, especially the latter, but to avoid a case where the Remotes content changes and I don't catch up to it, I'm pretty sure `desc` would, so I'd rather not just copy them over.

Would you consider exposing these two functions from the package?

_Happy to prepare a PR if welcome._

**Comment by gaborcsardi** [comment]
These would be fine indeed in desc, but they are actually in remotes now?

**Comment by nuest** [comment]
Ha, my bad: https://github.com/r-lib/remotes/issues/419
