### ISSUE TITLE
possible to style output with 80 character line maximum?

### ISSUE THREAD

**Issue by januz** [r-lib/desc#90]
Thanks for providing a way to create/modify a `DESCRIPTION` file programmatically! My problem is that the `Description: ` field I set using `desc` is longer than 80 characters. Is there a way to programmatically have the `DESCRIPTION` file be styled correctly, with no line longer than 80 characters and following lines indented? Thanks a lot!

**Comment by gaborcsardi** [comment]
You can `strwrap()` it to (say) 70 characters and add the newlines manually?

**Comment by januz** [comment]
works great, thank you! Do you think it would be a good idea to implement this in the package itself?

**Comment by gaborcsardi** [comment]
Doesn't `desc::desc_normalize()` do this already?

**Comment by januz** [comment]
Ha, it does! Sorry for not searching more thoroughly, that was the functionality I was after in the first place. Thank you so much for your help!

One thing I noticed is that `desc::desc_normalize()` also splits the `Title: ` field if it is over a certain length. If I understand it correctly, the `Title: ` field is supposed to only be one line. In my case, it's 68 characters and would fit comfortably in one line, but still is broken up by `desc::desc_normalize()`.

**Comment by gaborcsardi** [comment]
No, it does not have to be one line, and it is good if it is shorter:
> The mandatory ‘Title’ field should give a short description of the package. Some package listings may truncate the title to 65 characters.

https://cran.r-project.org/doc/manuals/R-exts.html
