### ISSUE TITLE
Add lifecycle

### ISSUE THREAD

**Issue by russellpierce** [r-lib/desc#98]
I've noticed a lot of r-lib stuff has a lifecycle noted for the package, but I didn't notice one among the badges for this package.  Consider adding so people have an idea about how much to depend on this package being around in the future.  Thanks!

**Comment by gaborcsardi** [comment]
True. desc is "stable". Do you want to submit a PR? :)

**Comment by russellpierce** [comment]
https://github.com/r-lib/desc/pull/99 now open to attempt to close this issue.
